name: Profile homework check

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Profile name"
        required: true

env:
  PROFILE: ${{ github.event.inputs.profile }}

jobs:
  run_test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run tests with profile
        run: mvn clean install -P$PROFILE
