name: Profile homework check

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Profile name"
        required: true

env:
  PROFILE: ${{ github.event.inputs.profile }}

jobs:
  run_test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run tests with profile
        uses: nanasess/setup-chromedriver@v1.0.1
        run: mvn clean install -P$PROFILE
