name: Homework checking

on:
  pull_request:
    branches:
      - master
    types: [ opened, reopened, synchronize ]

jobs:
  clean_compile:
    name: Check homework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: nanasess/setup-chromedriver@master
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Validate code
        run: mvn validate

      - name: Run tests
        run: mvn clean install
