name: Homework checking

on:
  pull_request:
    branches:
      - master
    types: [ opened, reopened, synchronize ]

jobs:
  validate:
    name: Check style
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Maven Validate
        run: mvn validate

  clean_install:
    name: Run tests
    runs-on: ubuntu-latest
    needs: [ validate ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Maven clean install
        run: mvn clean install
