name: Homework checking

on:
  pull_request:
    branches:
      - master
    types: [ opened, reopened, synchronize ]

jobs:
  clean_compile:
    name: Check homework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate code
        run: mvn validate

      - uses: actions/checkout@v2
      - name: Set up Chrome driver
        uses: nanasess/setup-chromedriver@v1
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &

      - name: Run tests
        run: mvn clean install
