name: Homework checking

on:
  pull_request:
    branches:
      - master
    types: [ opened, reopened, synchronize ]

jobs:
  clean_compile:
    name: Check homework
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore

      - name: Validate code
        run: mvn validate

      - name: Run tests
        uses: nanasess/setup-chromedriver@v1.0.1
        run: mvn clean install

      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save
